export const JOB_CATEGORIES = [
  { label: "All Jobs", value: "" },
  { label: "Software Development", value: "software_development" },
  { label: "Cybersecurity", value: "cybersecurity" },
  { label: "Customer Service", value: "customer_service" },
  { label: "Design", value: "design" },
  { label: "Marketing", value: "marketing" },
  { label: "Sales", value: "sales" },
  { label: "Product", value: "product" },
  { label: "Business", value: "business" },
  { label: "Data", value: "data" },
  { label: "DevOps", value: "devops" },
  { label: "Finance & Legal", value: "finance_legal" },
  { label: "Human Resources", value: "human_resources" },
  { label: "Quality Assurance", value: "qa" },
  { label: "Writing", value: "writing" },
  { label: "Project Management", value: "project_management" },
  { label: "Other", value: "all_others" },
];
